-- teardown.sql
TRUNCATE TABLE IF EXISTS hf_alerts RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS hf_usage RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS course_embeddings RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS shortlist_items RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS shortlists RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS courses RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS universities RESTART IDENTITY CASCADE;
-- Note: do not truncate profiles in case of real auth entries; only truncate synthetic profiles if created in seeds.
